const memeGenerateBtn=document.querySelector(".memeGenerator");
const memeTitle=document.querySelector(".memeTitle");
const memeAuthor=document.querySelector(".memeAuthor");
const memeImage=document.querySelector("img");

const updateMemeDetails = (url,title,author) =>{
    memeImage.setAttribute("src",url);
    memeAuthor.innerHTML=`Meme Generated by ${author}`;
    memeTitle.innerHTML=title;
}

const generateMeme = async() =>{
    const response = await fetch("https://meme-api.com/gimme/wholesomememes");
    const data = await response.json();
    updateMemeDetails(data.url,data.title,data.author);
}

memeGenerateBtn.addEventListener("click",()=>{
    generateMeme();
})

generateMeme();